FROM node:18-alpine
WORKDIR /app
COPY ./package.json .
COPY ./nodemon.json .
COPY ./tsconfig.json .
RUN yarn global add typescript
RUN yarn global add nodemon
RUN yarn install 
CMD ["yarn", "run", "dev"]