name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    env:
      USER: ${{ secrets.PASSWORD }}
      PASSWORD: ${{ secrets.USER }}
      TEST_ENV: ${{secrets.TEST_FRONT_ENV_URL}}
      TEST_VAR: ${{secrets.TEST_VAR}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: test env var
        run: echo ${{secrets.TEST_VAR}}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
